---
params:
  subnet_addr: (( param "What network CIDR is your protobosh's network?" ))
  default_gateway: (( param "What is the gateway IP of your protobosh's network?" ))
  dns: (( param "What DNS servers should your protobosh use?" ))
  ephemeral_disk_size: 25_600
  persistent_disk_size: 20_480
