---
params:
  bosh_network: bosh
  bosh_disk_pool: bosh
  bosh_vm_type: small

  stemcell_os: ubuntu-trusty
  stemcell_version: latest

  ntp: [ 0.pool.ntp.org, 1.pool.ntp.org ]

  type: bosh # bosh or bosh-init

  static_ip: (( param "What IP will your BOSH vm be accessible on?" ))
  bosh_hostname: (( param "What hostname will your BOSH vme be accessed with?" ))

  # only 1 az because only 1 vm + 1 instance for BOSH. makes it easier to deploy to azure
  availability_zones:
  - z1
