---
params:
  aws_subnet_id: (( param "Enter the AWS subnet ID for the proto-BOSH's subnet" ))
  aws_security_groups: (( param "Enter the list of security groups to be applied to your proto-BOSH" ))

  aws_instance_type: m3.xlarge
  aws_disk_type: gp2
